# Generated by Django 5.0.1 on 2024-06-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers_alter_category_name_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
    ]
