# Generated by Django 5.0.1 on 2024-06-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_name_category_category_name'),
        ('news', '0004_rename_category_category_name'),
    ]

    operations = [
    ]
